name: tests & build docker image
on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: run tests with code coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.20"   

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: go test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          env_vars: GO
        env:
          GO: ${{ matrix.go }}

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build & push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: duarty/golang-api:latest